### ISSUE TITLE
Switching Module Template

### ISSUE THREAD

**Issue by mattandwhatnot** [medienbaecker/kirby-modules#11]
switching the modules module template isn't working for me

template `module.text` to `module.difftext` just changes the page title to "module.difftext"

Running Kirby 3.4.1 + module plugin 0.6.3

I pretty sure it was working with Kirby 3.3 + plugin 0.6.2 but I haven't spun up a separate instance to confirm yet.

creating a new module with either template does work fine

**Comment by medienbaecker** [comment]
Please update Kirby to 3.4.2: https://github.com/getkirby/kirby/issues/2758

**Comment by mattandwhatnot** [comment]
o sorry missed that. Thanks so much.
