### ISSUE TITLE
Subpages message when deleting a page with modules field 

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#25]
First of all: Great plugin!
If an editor wants to delete a page he has to confirm by entering the page title even if there are no subpages and no modules.
I know it's because of the modules folder but in that case maybe it would be better to change this behaviour for an editor might be asking himself what's wrong...

![delete-page-has-subpages](https://user-images.githubusercontent.com/37336796/97975456-7300db00-1dc9-11eb-8606-52e43a2de8d6.png)

**Comment by medienbaecker** [comment]
Unfortunately I don't think there's an easy and future-proof way to overwrite this functionality.
Generally I try to avoid overwriting core functionality so the plugin doesn't break on Kirby updates.

**Comment by medienbaecker** [comment]
You can solve this yourself by adding a page model for the parent pages. I added instructions to the README: 
https://github.com/medienbaecker/kirby-modules#skipping-the-delete-confirmation-dialog
