### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by iskrisis** [medienbaecker/kirby-modules#27]
Hi @medienbaecker 

There is no information about license. I would like to use modules in my commercial theme. It would be pretty great if you could think about if you want something other than MIT license.

Thank you!

**Comment by medienbaecker** [comment]
Hi @iskrisis 👋 

Today I learned GitHub repositories are not open source by default. I added a LICENSE file and mentioned the MIT license in the README.md

**Comment by iskrisis** [comment]
Thank you for so quick action! I should also add license to projects. I think it's good it's not open source by default but i often forget.
Cheers!
