### ISSUE TITLE
QUESTION: can I have more than one section in a blueprint?

### ISSUE THREAD

**Issue by squareclouds** [medienbaecker/kirby-modules#35]
hi everyone. I want to create some specific modules in one section and others in a second one. is this possible? when I try it both show the same thing. if I add "templates" in the blueprint to filter them out, everything disappears in both and when i try to create a module in either one, the module gets treated as a page

**Comment by medienbaecker** [comment]
No, this is not possible. You'd need different [modules containers](https://github.com/medienbaecker/kirby-modules#whats-a-module).
