### ISSUE TITLE
create: proberty not working

### ISSUE THREAD

**Issue by hariom147** [medienbaecker/kirby-modules#36]
**Just tested this on a fresh starterkit:**

Using `modules: true`works fine.

But when using 
```
modules:
  type: modules
  create:
    - text
```
the create dialog shows only "Text" in the template list (not the actual title in `modules/text/text.yml` which is "Text Module") and creates a draft with text.txt, which actually shows fields defined in `default.yml` and not in `modules/text/text.yml`

What shows
<img width="464" alt="Bildschirmfoto 2022-07-15 um 14 06 43" src="https://user-images.githubusercontent.com/8297800/179220758-4d488dda-d093-466f-895c-ef28fcc73977.png">

What should show
<img width="463" alt="Bildschirmfoto 2022-07-15 um 14 07 03" src="https://user-images.githubusercontent.com/8297800/179220767-99d9d54d-5d32-4e5e-9431-8ad5509e2074.png">
.

**Comment by medienbaecker** [comment]
I think it should be module.text 🙂

**Comment by hariom147** [comment]
Thanks. That works. 🙂 
I first looked up your [earlier reply.](https://github.com/medienbaecker/kirby-modules/issues/32#issuecomment-976339875).
Where could I have derived prefixing the (module) template name with `module.`?
