### ISSUE TITLE
Prevent redirection to modules container on page deletion

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-modules#4]
When deleting a module you get redirected to the (otherwise invisible) modules container.

**Comment by medienbaecker** [comment]
Redirection in a panel hook is not possible (yet) since hooks can only interact via throwing Exceptions.

I'll try putting the redirection in a custom field that will be present on the modules container.

**Comment by medienbaecker** [comment]
Redirecting in a field doesn't seem trivial either.

For now there should be a blueprint for the modules container with an info field. It's not ideal, but better than displaying the default blueprint.

**Comment by nilshoerrmann** [comment]
My guess is you'd like to redirect to the module's grandparent page, the one containing the main content. I'm also assuming that Kirby is always redirecting to the direct parent after deleting a page. So have you tried changing the modules parent from the module container to the actual content page before deletion?

**Comment by medienbaecker** [comment]
@nilshoerrmann That's a great idea and I didn't think of this at all. Unfortunately—if I did everything right—it doesn't work either.

I added this hook:

```php
'page.delete:before' => function ($page) {
	if($page->parent()->intendedTemplate() == "modules") {
		$oldPageFolder = basename($page->contentFileDirectory());
		$newPageFolder = $page->parent()->parent()->contentFileDirectory() . DIRECTORY_SEPARATOR . $oldPageFolder;
		Dir::move($oldPageFolder, $newPageFolder);
	}
}
```

But it still redirects to the modules container page. I think the variables are set before the `:before` hook or something like that?

**Comment by nilshoerrmann** [comment]
Okay, I'm only guessing, but maybe it's possible to manipulate the `$page` object that is passed to the hook. So maybe you could just make the page "think" that it has a different parent without actually moving folders?

**Comment by medienbaecker** [comment]
I spent hours trying to get this redirection to work—no chance. For now I added a link to the parent page in the modules blueprint. This way you can at least get to the parent page with one click.

**Comment by nilshoerrmann** [comment]
Maybe you could ask Bastian, if it's possible at all. 
Does Kirby allow for custom routes for the panel maybe?

**Comment by medienbaecker** [comment]
![image](https://user-images.githubusercontent.com/7975568/74252023-537ecb00-4ced-11ea-8e39-b57ccfddfcf5.png)

Unfortunately it seems like there's no solution for this.

**Comment by medienbaecker** [comment]
I think I found a solution. It's quite hacky but it works:

The modules plugin now includes a simple `modules_redirect` field.
I pass [`$this->model()->parent()->panelUrl()`](https://github.com/medienbaecker/kirby-modules/blob/feature/modules_redirect/index.php#L62-L64) to it and redirect to this url on [`render`](https://github.com/medienbaecker/kirby-modules/blob/feature/modules_redirect/src/index.js#L13).

You can check it out in the branch [feature/modules_redirect](https://github.com/medienbaecker/kirby-modules/tree/feature/modules_redirect).

**Comment by nilshoerrmann** [comment]
Hacky – but clever! 👍
