### ISSUE TITLE
Modules status texts

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#45]
Replace page width module in status text:

![modules-status](https://github.com/medienbaecker/kirby-modules/assets/37336796/f9d01104-2630-4381-bb21-92cb3d442aea)

Of course this could just be done individually in the blueprints but I think just replacing page with module would be nice...

**Comment by medienbaecker** [comment]
Good point! Because this text has to be translated to multiple languages, this feature needs some refactoring first. Unfortunately I can't access the plugins' translations so early.

**Comment by medienbaecker** [comment]
There seems to be no way for me to use localised texts while replacing "page" with "module" so instead I simply removed the descriptions in version 2.8.1.
