### ISSUE TITLE
Reuse module options

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#46]
I try to reuse module options but get an error in the kirby panel.
For normal pages this way of reusing options works.

![Reuse module options](https://github.com/medienbaecker/kirby-modules/assets/37336796/8002337f-de22-493b-91a8-f1584d04dbbf)

I don't know if it's really an issue or I'm doing something wrong...

**Comment by medienbaecker** [comment]
The `changeTemplate` option (among others) is automatically generated. Is there a reason why you want to define it manually?

**Comment by tan3ot** [comment]
I just want to reuse this option for I've some default modules and another modules set. When I add/remove module to/from a set this could be done in one place. But it is not really important just copy'n'paste a few times to achieve this...
Ideally, only the list items would be outsourced anyway, then you could also use this in "create". But that doesn't work anyway.

**Comment by medienbaecker** [comment]
I don't have easy access to the file you're extending. So all I can do for now is check if `options` is a string (in your case `options/module` instead of an array and stop the automatic `changeTemplate` population.

Does the latest release work for you?

**Comment by tan3ot** [comment]
Yes, this works! Thanks a lot :-)
