### ISSUE TITLE
Changing slug empties text field

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#47]
When changing a module slug the text of a text (writer field) disappears?
To reproduce: 

![Bildschirmfoto 2024-06-14 um 18 35 40](https://github.com/medienbaecker/kirby-modules/assets/37336796/f7087ab1-162a-4ff7-a592-cf085e49a9ec)

Than fill in the text field.
Change the slug of the module.
On save the text disappears.

https://github.com/medienbaecker/kirby-modules/assets/37336796/012582c3-a42c-43ae-8884-4a4a1bde3ed4

Thanks for your support!

**Comment by medienbaecker** [comment]
Does this only happen for modules or also for any other page with a `writer` field? There's a known issue, but it's unrelated to this plugin: https://github.com/getkirby/kirby/issues/5659

**Comment by tan3ot** [comment]
Oh, this happens for every writer field. So it seems not to be a modules plugin issue. 
I add a comment in this issue: [getkirby/kirby/#6351](https://github.com/getkirby/kirby/issues/6351)
